package tampilan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import koneksi.Koneksi;
/**
 * MUH, SYAHRUL WAJHULLAH JASMAN 123170094
 * PRUDENCA AHMAD DAFFA 123190005
 */
public class Pelanggan extends javax.swing.JFrame {
    
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;

    /** Creates new form Dashboard */
    public Pelanggan() {
        initComponents();
        String[] judul = {
            "No Transaksi", "Nama", "No Telp", "Alamat", 
            "Mobil", "No Plat", "Sopir", "No Telp Sopir", "Tanggal Sewa",
            "Tanggal Kembali", "Keterangan"
        };
        tabmode = new DefaultTableModel(judul, 0);
        tablePelanggan.setModel(tabmode);
        tampilkan();
        tampilCombo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupKet = new javax.swing.ButtonGroup();
        groupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnDaftarMobil = new javax.swing.JButton();
        btnDaftarSopir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldKTP = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        radioPria = new javax.swing.JRadioButton();
        radioWanita = new javax.swing.JRadioButton();
        fieldAlamat = new javax.swing.JTextField();
        fieldSewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboMobil = new javax.swing.JComboBox<>();
        comboSopir = new javax.swing.JComboBox<>();
        fieldTanggal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        radioLunas = new javax.swing.JRadioButton();
        radioDP = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        fieldTelp = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 222, 222));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 85, 139));
        jPanel1.setForeground(new java.awt.Color(51, 85, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(189, 600));

        jPanel2.setBackground(new java.awt.Color(39, 73, 127));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        btnDashboard.setBackground(new java.awt.Color(51, 85, 139));
        btnDashboard.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(254, 254, 254));
        btnDashboard.setText("Dashboard");
        btnDashboard.setMaximumSize(new java.awt.Dimension(128, 38));
        btnDashboard.setPreferredSize(new java.awt.Dimension(128, 38));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDaftarMobil.setBackground(new java.awt.Color(51, 85, 139));
        btnDaftarMobil.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnDaftarMobil.setForeground(new java.awt.Color(254, 254, 254));
        btnDaftarMobil.setText("Daftar Mobil");
        btnDaftarMobil.setPreferredSize(new java.awt.Dimension(128, 38));
        btnDaftarMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarMobilActionPerformed(evt);
            }
        });

        btnDaftarSopir.setBackground(new java.awt.Color(51, 85, 139));
        btnDaftarSopir.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnDaftarSopir.setForeground(new java.awt.Color(254, 254, 254));
        btnDaftarSopir.setText("Daftar Sopir");
        btnDaftarSopir.setPreferredSize(new java.awt.Dimension(165, 38));
        btnDaftarSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarSopirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaftarMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaftarSopir, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnDaftarMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDaftarSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(149, 166, 176));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 79, 101));
        jLabel3.setText("Daftar Pelanggan");

        btnTambah.setBackground(new java.awt.Color(51, 85, 139));
        btnTambah.setForeground(new java.awt.Color(254, 254, 254));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnTambah.setText("Tambah Pelanggan");
        btnTambah.setPreferredSize(new java.awt.Dimension(98, 32));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "No Telepon", "Alamat", "Mobil", "No Plat", "Sopir", "No Telp", "Sewa", "Kembali", "Keterangan"
            }
        ));
        tablePelanggan.setMaximumSize(new java.awt.Dimension(600, 108));
        tablePelanggan.setPreferredSize(new java.awt.Dimension(600, 108));
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePelanggan);

        btnHapus.setBackground(new java.awt.Color(51, 85, 139));
        btnHapus.setForeground(new java.awt.Color(254, 254, 254));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cross.png"))); // NOI18N
        btnHapus.setText("Hapus Pelanggan");
        btnHapus.setPreferredSize(new java.awt.Dimension(98, 32));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(51, 85, 139));
        btnEdit.setForeground(new java.awt.Color(254, 254, 254));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit Pelanggan");
        btnEdit.setPreferredSize(new java.awt.Dimension(98, 32));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("No. KTP                   :");

        jLabel5.setText("Nama                      :");

        jLabel6.setText("Jenis Kelamin         :");

        jLabel7.setText("Alamat                    :");

        jLabel8.setText("Sewa                       :");

        jLabel9.setText("Mobil                       :");

        jLabel10.setText("Sopir                       :");

        jLabel11.setText("Tanggal Kembali  :");

        jLabel12.setText("Keterangan           :");

        groupGender.add(radioPria);
        radioPria.setText("Pria");

        groupGender.add(radioWanita);
        radioWanita.setText("Wanita");

        jLabel13.setText("Hari");

        comboMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Mobil" }));

        comboSopir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Sopir" }));

        jLabel14.setText("Format -> YYYY-MM-DD (contoh: 2021-06-27)");

        groupKet.add(radioLunas);
        radioLunas.setText("Lunas");

        groupKet.add(radioDP);
        radioDP.setText("DP 50 %");

        jLabel15.setText("No. Telp                   :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldKTP)
                            .addComponent(fieldNama)
                            .addComponent(fieldAlamat)
                            .addComponent(comboMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboSopir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(radioPria)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioWanita))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(fieldSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(radioLunas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioDP)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTelp)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radioPria)
                    .addComponent(radioWanita))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fieldTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radioLunas)
                    .addComponent(radioDP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClear.setBackground(new java.awt.Color(51, 85, 139));
        btnClear.setForeground(new java.awt.Color(254, 254, 254));
        btnClear.setText("C");
        btnClear.setPreferredSize(new java.awt.Dimension(32, 32));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(253, 18, 29));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signoutK.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(200, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        // TODO add your handling code here:
        comboSopir.removeAllItems();
        comboMobil.removeAllItems();
        comboMobil.addItem("-Pilih Mobil");
        comboSopir.addItem("-Pilih Sopir");
        tampilCombo();
        fieldKTP.setEditable(false);
        fieldKTP.requestFocus();
        int i = tablePelanggan.getSelectedRow();
        if (i >- 1) {
            try {
                ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM pelanggan WHERE no_transaksi = '" 
                    + tabmode.getValueAt(i, 0).toString() + "'");
                while (rs.next()) {
                    fieldKTP.setText(rs.getString("no_ktp"));
                    fieldSewa.setText(rs.getString("hari_sewa"));
                    if ("Pria".equalsIgnoreCase(rs.getString("jenis_kelamin"))) {
                        radioPria.setSelected(true);
                    } else {
                        radioWanita.setSelected(true);
                    }
                }
            } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
            fieldNama.setText(tabmode.getValueAt(i, 1).toString());
            
            fieldTelp.setText(tabmode.getValueAt(i, 2).toString());
            fieldAlamat.setText(tabmode.getValueAt(i, 3).toString());
            
            comboMobil.addItem((tabmode.getValueAt(i, 4).toString()) + " (" + (tabmode.getValueAt(i, 5).toString()) + ")");
            comboMobil.setSelectedItem((tabmode.getValueAt(i, 4).toString()) + " (" + (tabmode.getValueAt(i, 5).toString()) + ")");
            comboSopir.addItem((tabmode.getValueAt(i, 6).toString()) + " (" + (tabmode.getValueAt(i, 7).toString()) + ")");
            comboSopir.setSelectedItem((tabmode.getValueAt(i, 6).toString()) + " (" + (tabmode.getValueAt(i, 7).toString()) + ")");
            
            fieldTanggal.setText(tabmode.getValueAt(i, 9).toString());
            
            if ("Lunas".equalsIgnoreCase(tabmode.getValueAt(i, 10).toString())) {
                radioLunas.setSelected(true);
            } else {
                radioDP.setSelected(true);
            }
            
        }
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String tanggal = fieldTanggal.getText();
        String noTransaksi = tanggal.replace("-", "") + fieldKTP.getText();
        
        String JK;
        if (radioPria.isSelected()) {
            JK = "Pria";
        } else if (radioWanita.isSelected()) {
            JK = "Wanita";
        } else {
            JK = "";
        }
        
        String Ket;
        int Profit;
        if (radioDP.isSelected()) {
            Ket = "DP 50 %";
            Profit = 100000;
        } else if (radioLunas.isSelected()) {
            Ket = "Lunas";
            Profit = 200000;
        } else {
            Ket = "";
            Profit = 0;
        }
        if ( Profit != 0)
            JOptionPane.showMessageDialog(null, "Total Pembayaran Rp. " 
                    + Integer.parseInt(fieldSewa.getText()) * Profit);
        
         if ("".equals(fieldKTP.getText()) || "".equals(fieldNama.getText()) || 
                "".equals(fieldSewa.getText()) || "".equals(fieldTelp.getText())
                || "".equals(fieldAlamat.getText()) || "".equals(fieldTanggal.getText()) ) {
            JOptionPane.showMessageDialog(this, 
                    "Harap melengkapi data terlebih dahulu", "ERROR", 
                    JOptionPane.WARNING_MESSAGE);
        } else if ("".equals(Ket) || "".equals(JK) ||
                "-Pilih Mobil".equals(comboMobil.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, 
                    "Harap memilih data terlebih dahulu", "ERROR", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            String cMblStr = (String) comboMobil.getSelectedItem();
            int awalM = cMblStr.indexOf("(");
            int akhirM = cMblStr.indexOf(")");
            String noPlat = cMblStr.substring(awalM+1, akhirM);
            String namaMobil = cMblStr.substring(0, awalM-1);

            String cSprStr = (String) comboSopir.getSelectedItem();
            String noHP;
            String namaSopir;
             if (cSprStr == "-Pilih Sopir") {
                 noHP = "";
                 namaSopir = "";
             } else {
                 int awalS = cSprStr.indexOf("(");
                 int akhirS = cSprStr.indexOf(")");
                 noHP = cSprStr.substring(awalS+1, akhirS);
                 namaSopir = cSprStr.substring(0, awalS-1);
             }
            
            try {
            conn.createStatement().executeUpdate("INSERT INTO pelanggan SET "
                    + "no_transaksi = '" + noTransaksi + "',"
                    + "no_ktp = '" + fieldKTP.getText() + "',"
                    + "nama = '" + fieldNama.getText() + "'," 
                    + "jenis_kelamin = '" + JK + "'," 
                    + "no_telp = '" + fieldTelp.getText() + "',"
                    + "alamat = '" + fieldAlamat.getText() + "',"
                    + "hari_sewa = '" + fieldSewa.getText() + "',"
                    + "mobil = '" + namaMobil + "',"
                    + "no_plat = '" + noPlat + "',"
                    + "sopir = '" + namaSopir + "',"
                    + "no_telp_sopir = '" + noHP + "',"
                    + "tgl_kembali = '" + fieldTanggal.getText() + "',"
                    + "profit = '" + Integer.parseInt(fieldSewa.getText()) * Profit + "',"
                    + "ket = '" + Ket 
                    + "';");
            comboSopir.removeAllItems();
            comboMobil.removeAllItems();
            tampilkan();
            reset();
            tampilCombo();
            fieldKTP.requestFocus();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data gagal disimpan, " + ex);
        }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String JK;
        if (radioPria.isSelected()) {
            JK = "Pria";
        } else {
            JK = "Wanita";
        }
        
        String Ket;
        int Profit;
        if (radioDP.isSelected()) {
            Ket = "DP 50 %";
            Profit = 0;
        } else if (radioLunas.isSelected()) {
            Ket = "Lunas";
            Profit = 100000;
        } else {
            Ket = "";
            Profit = 0;
        }
        if ( Profit != 0)
            JOptionPane.showMessageDialog(null, "Total Pembayaran Rp. " 
                    + Integer.parseInt(fieldSewa.getText()) * Profit);
        
         if ("".equals(fieldKTP.getText()) || "".equals(fieldNama.getText()) || 
                "".equals(fieldSewa.getText()) || "".equals(fieldTelp.getText())
                || "".equals(fieldAlamat.getText()) || "".equals(fieldTanggal.getText()) ) {
            JOptionPane.showMessageDialog(this, 
                    "Harap melengkapi data terlebih dahulu", "ERROR", 
                    JOptionPane.WARNING_MESSAGE);
        } else if ("".equals(Ket) || "".equals(JK) ||
                "-Pilih Mobil".equals(comboMobil.getSelectedItem()) ||
                "-Pilih Sopir".equals(comboSopir.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, 
                    "Harap memilih data terlebih dahulu", "ERROR", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            String cMblStr = (String) comboMobil.getSelectedItem();
            int awalM = cMblStr.indexOf("(");
            int akhirM = cMblStr.indexOf(")");
            String noPlat = cMblStr.substring(awalM+1, akhirM);
            String namaMobil = cMblStr.substring(0, awalM-1);

            String cSprStr = (String) comboSopir.getSelectedItem();
            int awalS = cSprStr.indexOf("(");
            int akhirS = cSprStr.indexOf(")");
            String noHP = cSprStr.substring(awalS+1, akhirS);
            String namaSopir = cSprStr.substring(0, awalS-1);
            
            try {
            conn.createStatement().executeUpdate("UPDATE pelanggan SET "
                    + "nama = '" + fieldNama.getText() + "'," 
                    + "jenis_kelamin = '" + JK + "'," 
                    + "no_telp = '" + fieldTelp.getText() + "',"
                    + "alamat = '" + fieldAlamat.getText() + "',"
                    + "hari_sewa = '" + fieldSewa.getText() + "',"
                    + "mobil = '" + namaMobil + "',"
                    + "no_plat = '" + noPlat + "',"
                    + "sopir = '" + namaSopir + "',"
                    + "no_telp_sopir = '" + noHP + "',"
                    + "tgl_kembali = '" + fieldTanggal.getText() + "',"
                    + "profit = '" + 100000 + Integer.parseInt(fieldSewa.getText()) * Profit + "',"
                    + "ket = '" + Ket
                    + "' WHERE no_ktp = '" + fieldKTP.getText() 
                    + "'");
            comboSopir.removeAllItems();
            comboMobil.removeAllItems();
            tampilkan();
            reset();
            tampilCombo();
            fieldKTP.requestFocus();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data gagal diubah, " + ex);
        }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin anda ingin Menghapus?", "Konfirmasi ", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == 0 ) {
            try {
            conn.createStatement().executeUpdate("DELETE FROM pelanggan WHERE no_ktp = '" 
                    + fieldKTP.getText() + "'");
            comboSopir.removeAllItems();
            comboMobil.removeAllItems();
            tampilkan();
            reset();
            tampilCombo();
            fieldKTP.setEditable(true);
            fieldKTP.requestFocus();
            JOptionPane.showMessageDialog(null, "Data berhasil hapus");
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data gagal dihapus, " + ex);
        }
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        comboSopir.removeAllItems();
        comboMobil.removeAllItems();
        reset();
        tampilCombo();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDaftarMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarMobilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Mobil mobil = new Mobil();
        mobil.setVisible(true);
    }//GEN-LAST:event_btnDaftarMobilActionPerformed

    private void btnDaftarSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarSopirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Sopir sopir = new Sopir();
        sopir.setVisible(true);
    }//GEN-LAST:event_btnDaftarSopirActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void reset() {
        fieldKTP.setText("");
        fieldNama.setText("");
        fieldTelp.setText("");
        fieldAlamat.setText("");
        fieldSewa.setText("");
        comboMobil.addItem("-Pilih Mobil");
        comboSopir.addItem("-Pilih Sopir");
        fieldTanggal.setText("");
        groupGender.clearSelection();
        groupKet.clearSelection();
        fieldKTP.setEditable(true);
    }
    
    private void tampilkan() {
        int i = 1;
        int row = tablePelanggan.getRowCount();
        for (int a = 0; a < row; a++) {
            tabmode.removeRow(0);
        }
        try {
            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM pelanggan");
            while (rs.next()) {
                String index = Integer.toString(i);
                String[] data = {
                    rs.getString(1), rs.getString(3), 
                    rs.getString(5), rs.getString(6),
                    rs.getString(8), rs.getString(9), 
                    rs.getString(10), rs.getString(11), rs.getString(12),
                    rs.getString(13), rs.getString(15)
                };
                i++;
                tabmode.addRow(data);
            }
            fieldKTP.setEditable(true);
            System.out.println("Koneksi Berhasil");
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data Gagal dipanggil " + ex);
        }
    }
    
    private void tampilCombo(){
        try {
            conn.createStatement().executeUpdate("UPDATE mobil SET "
                    + "status = 'Tersedia'");
            conn.createStatement().executeUpdate("UPDATE sopir SET "
                    + "ket = 'Ada'");
            
            ResultSet rsPelanggan = conn.createStatement().executeQuery("SELECT no_plat, no_telp_sopir FROM pelanggan");
            
            while (rsPelanggan.next()) {
                conn.createStatement().executeUpdate("UPDATE mobil SET "
                    + "status = 'Disewa'"
                    + " WHERE plat = '" + rsPelanggan.getString("no_plat")
                    + "'");
                conn.createStatement().executeUpdate("UPDATE sopir SET "
                    + "ket = 'Tidak Ada'"
                    + " WHERE no_telp = '" + rsPelanggan.getString("no_telp_sopir")
                    + "'");
            }
            
            
            ResultSet rsMobil = conn.createStatement().executeQuery("SELECT * FROM mobil WHERE status = 'Tersedia'");
            while (rsMobil.next()) {
                String namaMobil = rsMobil.getString("nama");
                String noPlat = rsMobil.getString("plat");
                comboMobil.addItem(namaMobil + " (" + noPlat + ")");
            }
            
            ResultSet rsSopir = conn.createStatement().executeQuery("SELECT * FROM sopir WHERE ket = 'Ada'");
            while (rsSopir.next()) {
                String nama = rsSopir.getString("nama");
                String no = rsSopir.getString("no_telp");
                comboSopir.addItem(nama + " (" + no + ")");
            }
         } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDaftarMobil;
    private javax.swing.JButton btnDaftarSopir;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> comboMobil;
    private javax.swing.JComboBox<String> comboSopir;
    private javax.swing.JTextField fieldAlamat;
    private javax.swing.JTextField fieldKTP;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldSewa;
    private javax.swing.JTextField fieldTanggal;
    private javax.swing.JTextField fieldTelp;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.ButtonGroup groupKet;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDP;
    private javax.swing.JRadioButton radioLunas;
    private javax.swing.JRadioButton radioPria;
    private javax.swing.JRadioButton radioWanita;
    public javax.swing.JTable tablePelanggan;
    // End of variables declaration//GEN-END:variables

}
